### PR TITLE
new SuiteSparse database

### PR DESCRIPTION
**Pull request by dpo**
This database has more features than the previous one, is up to date,
and does not contain incomplete information.
It can be easily updated using a script supplied in the utils folder.

### CODE REVIEW

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
At the end of the `README.md`, you could add `Matrices in RB format can be opened with [`HarwellRutherfordBoeing.jl`](https://github.com/JuliaSparse/HarwellRutherfordBoeing.jl).

**Comment by dpo** [comment]
It already says that, doesn't it?

**Comment by amontoison** [comment]
> It already says that, doesn't it?

Nop, you only explain which packages are used to read `MAT` and `MM`formats.

**Comment by dpo** [comment]
No, it says right there: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R67

**Comment by amontoison** [comment]
> No, it says right there: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/pull/14/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R67

You're right, I missed it.

**Pull request merged**
