### PR TITLE
Avoid to re-download files

### LINKED ISSUE #28: Re-download files
Hi,
Apparently when a fetch_ssmc is executed, the matrices already downloaded are download again.
This is critical if large matrices is included in several fetch_ssmc.
In addition, this causes unnecessary writting to the hard drive.

### PR DESCRIPTION
**Pull request by amontoison**
fix #28

### CODE REVIEW

**Comment by dpo** [comment]
This will all be superseded by #26 very soon, but why don’t we simply remove the line that deletes the tar.gz in the mean time?

In what sense aren’t mtx files handled properly? They are also packaged in tar.gz archives.

**Comment by amontoison** [comment]
Why do you want to keep the `tar.gz` files ?
The main issue is that we check if the `tar.gz` files are downloaded or not but they are only temporary files.
It's the matrices `.rb` and `.mtx` files that should be checked.

**Comment by dpo** [comment]
I understand but I'm not sure I agree. I see now that the tar.gz is downloaded in some strange location. We could move it to the same location as the matrices. The issue is that certain systems come with a right-hand side, some not, some come with other information. Moreover, it's the tar.gz files that we download; they are the only thing we can reliably check.

**Comment by amontoison** [comment]
But how to distinguish the `tar.gz` downloaded for `.mtx` and `.rb` matrices ? The archive has the same name.

**Comment by amontoison** [comment]
We can merge #26 but we should wait the end of the session for a new release.

**Pull request closed without merging**
